apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-sample-dep
  namespace: touches-online-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-sample-dep
  template:
    metadata:
      labels:
        app: fastapi-sample-dep
    spec:
      containers:
        - name: fastapi-sample-dep
          image: k3d-touches-online-registry:5050/fastapi-sample:latest
          ports:
            - containerPort: 3050